### ISSUE TITLE
Problem when adapter has 2 or more ViewType

### ISSUE THREAD

**Issue by euitam** [ismoli/DynamicRecyclerView#1]
Hi,

nice library :-) but I tried to use it in a recycler view with two types of view (so 2 viewHolders) and when you swap two items which are not of the same type, the items swapped are becoming invisible until you make a new long press on them... I have quickly read your code, but I don't know yet from where the problem is coming.

**Comment by ismoli** [comment]
Hi
It is hard to say where is your problem, as this lib does not include this functionality out of the box (and should not as it is not providing special adapter for your data), but I believe you can easily implement this in your RecyclerViewAdapter.
