### ISSUE TITLE
Horizontal LinearManager support

### ISSUE THREAD

**Issue by meoyawn** [ismoli/DynamicRecyclerView#2]
Hello and thanks for the great lib!

I wanted to add a horizontal linear manager support, can you please help me by pointing out places in code where I can play and add horizontal support?

Cheers!

**Comment by ismoli** [comment]
Hi, to play with it you just need to provide your  HorizontalLayoutManager to the RecyclerView when you constructing it.
something like 
`RecyclerView recyclerView = (RecyclerView) findViewById(R.id.list);
        recyclerView.setLayoutManager(new HorizontalLayoutManager(this));`

**Comment by meoyawn** [comment]
Thank you very much!
